server:
  addr: "0.0.0.0"
  port: 8080
  max-file-size: 10485760
  file-path: "./files/"
telegram:
  token: ""
  url: ""
sqlite:
  driver-name: "sqlite3"
  path: "storage/database.db"
  migration-path: "migrations/sqlite/"
